### ISSUE TITLE
Install postgres

### ISSUE THREAD

**Issue by tajkhan** [Uzair-90/practice#6]
Install postgres with IMDB data.
Do HW1 of CMU database course.

**Comment by Uzair-90** [comment]
done

**Comment by Uzair-90** [comment]
I have done the home work.

**Comment by Uzair-90** [comment]
CMU homework is done.

**Comment by tajkhan** [comment]
@Uzair-90 , I see that you've closed this issue. So were you able breakdown and understand the last 2 queries in full?
